### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by 0Navis0** [MehVahdJukaar/WoodGood#135]
```
[17:15:46] [Render thread/WARN]: failed to apply azalea overlay: 
java.lang.IllegalStateException: Could not merge images because they had different dimensions
	at net.mehvahdjukaar.moonlight.api.resources.textures.TextureImage.applyOverlayOnExisting(TextureImage.java:294) ~[moonlight-1.19.2-2.2.2-forge.jar%23227!/:?]
	at net.mehvahdjukaar.every_compat.api.CompatModule.maybeFlowerAzalea(CompatModule.java:196) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at net.mehvahdjukaar.every_compat.api.CompatModule.lambda$addWoodTexture$0(CompatModule.java:178) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynClientResourcesProvider.addTextureIfNotPresent(DynClientResourcesProvider.java:61) ~[moonlight-1.19.2-2.2.2-forge.jar%23227!/:?]
	at net.mehvahdjukaar.every_compat.api.CompatModule.addWoodTexture(CompatModule.java:176) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at net.mehvahdjukaar.every_compat.api.SimpleEntrySet.generateTextures(SimpleEntrySet.java:388) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.lambda$addDynamicClientResources$8(SimpleModule.java:97) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.addDynamicClientResources(SimpleModule.java:97) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$2(ClientDynamicResourcesHandler.java:56) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.forAllModules(EveryCompat.java:55) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ClientDynamicResourcesHandler.regenerateDynamicAssets(ClientDynamicResourcesHandler.java:54) ~[everycomp-1.19.2-2.2.3.jar%23216!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:111) ~[moonlight-1.19.2-2.2.2-forge.jar%23227!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.onEarlyReload(DynResourceProvider.java:81) ~[moonlight-1.19.2-2.2.2-forge.jar%23227!/:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.lambda$postEvent$4(MoonlightEventsHelperImpl.java:44) ~[moonlight-1.19.2-2.2.2-forge.jar%23227!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:44) ~[moonlight-1.19.2-2.2.2-forge.jar%23227!/:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.19.2-2.2.2-forge.jar%23227!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.handler$bdd000$dynamicPackEarlyReload(MultiPackResourceManager.java:534) ~[client-1.19.2-20220805.130853-srg.jar%23249!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.<init>(MultiPackResourceManager.java:61) ~[client-1.19.2-20220805.130853-srg.jar%23249!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:44) ~[client-1.19.2-20220805.130853-srg.jar%23249!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:577) ~[client-1.19.2-20220805.130853-srg.jar%23249!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23249!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23249!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

**Comment by Xelbayria** [comment]
Is this issue resolved in the latest version? if yes, then please close this issue. 

Otherwise, please fill out the info: 
- Minecraft Version: ??
- Loader (Forge or Fabric): ???
- Which mods does Every Compat have an issue with: ???

Also, you need to attach the file with the log (everything in it) in here.
