### ISSUE TITLE
Server-Side Crash for Fabric 0.14.19

### ISSUE THREAD

**Issue by ereese99** [MehVahdJukaar/WoodGood#154]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'everycomp'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1087
	at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.lambda$onInitialize$12(EveryCompatFabric.java:40) ~[everycomp-1.19.2-2.3.4-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.addModule(EveryCompat.java:123) ~[everycomp-1.19.2-2.3.4-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.onInitialize(EveryCompatFabric.java:40) ~[everycomp-1.19.2-2.3.4-fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1087
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.lambda$onInitialize$12(EveryCompatFabric.java:40) ~[everycomp-1.19.2-2.3.4-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.addModule(EveryCompat.java:123) ~[everycomp-1.19.2-2.3.4-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.onInitialize(EveryCompatFabric.java:40) ~[everycomp-1.19.2-2.3.4-fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 7 more

That's the log upon startup.

**Comment by TigerWalts** [comment]
I have narrowed this down to an incompatibility between **Create** and **Every Compat**

Fabric: `1.19.2 0.14.19`

Mods:

- create-fabric-0.5.0.i-991+1.19.2.jar
- everycomp-1.19.2-2.3.4-fabric.jar
- fabric-api-0.76.0+1.19.2.jar
- moonlight-1.19.2-2.2.29-fabric.jar

Log:

- [latest.log](https://gist.github.com/TigerWalts/b9f81d8d7ae9c819a21f337a3202a324)

---

The server will not crash if you downgrade **Every Compat** to version `1.19.2-2.2.2`.

**Comment by TorchTheDragon** [comment]
I have tested, issue is fixed in `1.19.2-2.4.6`

**Comment by dKatsuro** [comment]
Currently experiencing this issue as well.

I am running this in a Modpack. Basically the Better Minecraft pack with Create (and some Create addons) and AE2 added into it.

- create-fabric-0.5.0.i-1003+1.19.2.jar
- everycomp-1.19.2-2.4.7-fabric.jar
- fabric-api-0.76.0+1.19.2.jar
- moonlight-1.19.2-2.2.32-fabric.jar

Here is my [latest.log](https://pastebin.com/raw/6pv5YyX3).
Full mod list in the pack [is here](https://pastebin.com/raw/yBYmpktZ).

Some of the Create related additions:
- Create Deco Casing 2.0.0 1.19 Fabric.jar
- create-fabric-0.5.0.i-1003+1.19.2.jar
- createaddition-fabric+1.19.2-20230508b.jar
- createdeco-1.3.2-1.19.2.jar
- CreateFabricREIBugFix-0.1.2-mc1.19.x.jar

I'll experiment without the additions and stuff like that to see if I can find which one is conflicting.

**Comment by dKatsuro** [comment]
Tested launching a server with just the following:
- create-fabric-0.5.0.i-1003+1.19.2.jar
- everycomp-1.19.2-2.4.7-fabric.jar
- fabric-api-0.76.0+1.19.2.jar
- moonlight-1.19.2-2.2.32-fabric.jar
Works fine.

So was thinking maybe a furniture mod or something?
Tried with [the following mod list](https://pastebin.com/raw/ejKKGrHY) and it still works fine. Granted, there are quite a few other furniture mods in the pack I have that I haven't added to the test but I'm just going to remove Every Compat for now.

**Comment by MehVahdJukaar** [comment]
Update twigs

**Comment by dKatsuro** [comment]
That did it, thanks!
