### ISSUE TITLE
Many warn with betterX and BiomeMakeOver

### ISSUE THREAD

**Issue by SettingDust** [MehVahdJukaar/WoodGood#196]
There is apart of them. ModernFix enabled dynamic resource. And monnklight is the latest that added the support
```
[22:59:05] [Render thread/WARN] (Minecraft) Exception loading blockstate definition: 'everycomp:blockstates/mcf/betterend/mossy_glowshroom_picket_fence.json' missing model for variant: 'everycomp:mcf/betterend/mossy_glowshroom_picket_fence#east=false,fluidlogged=1,north=true,north_east=false,north_west=false,south=false,south_east=true,south_west=true,waterlogged=false,west=false'
[22:52:18] [Render thread/WARN] (Minecraft) Exception loading blockstate definition: 'everycomp:blockstates/mcf/betternether/anchor_tree_picket_fence.json' missing model for variant: 'everycomp:mcf/betternether/anchor_tree_picket_fence#east=false,fluidlogged=0,north=false,north_east=false,north_west=true,south=false,south_east=false,south_west=false,waterlogged=true,west=false'
[22:56:10] [Render thread/WARN] (Minecraft) Exception loading blockstate definition: 'everycomp:blockstates/mcf/betterend/jellyshroom_picket_fence.json' missing model for variant: 'everycomp:mcf/betterend/jellyshroom_picket_fence#east=false,fluidlogged=0,north=true,north_east=true,north_west=false,south=false,south_east=true,south_west=true,waterlogged=false,west=false'
[22:57:50] [Render thread/WARN] (Minecraft) Exception loading blockstate definition: 'everycomp:blockstates/mcf/betternether/wart_wired_fence.json' missing model for variant: 'everycomp:mcf/betternether/wart_wired_fence#east=false,fluidlogged=0,north=true,north_east=true,north_west=false,south=true,south_east=false,south_west=true,waterlogged=false,west=true'
[22:59:06] [Render thread/WARN] (Minecraft) Exception loading blockstate definition: 'everycomp:blockstates/mcf/betterend/pythadendron_picket_fence.json' missing model for variant: 'everycomp:mcf/betterend/pythadendron_picket_fence#east=false,fluidlogged=1,north=false,north_east=false,north_west=false,south=false,south_east=true,south_west=false,waterlogged=true,west=true'
[22:53:35] [Render thread/WARN] (Minecraft) Exception loading blockstate definition: 'everycomp:blockstates/mcf/betternether/nether_reed_picket_fence.json' missing model for variant: 'everycomp:mcf/betternether/nether_reed_picket_fence#east=false,fluidlogged=0,north=true,north_east=false,north_west=false,south=false,south_east=true,south_west=true,waterlogged=false,west=false'
```

Something may related
```
[22:51:24] [Render thread/ERROR] (ImmersiveWeathering) Failed to find log texture for bark betternether:nether_reed
java.io.IOException: java.util.NoSuchElementException: No value present
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:28) ~[transformed-mod-moonlight.i0:0/:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.TextureImage.open(TextureImage.java:149) ~[transformed-mod-moonlight.i0:0/:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$9(ClientDynamicResourcesHandler.java:264) ~[transformed-mod-immersive-weathering.i0:0/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
```

**Comment by MehVahdJukaar** [comment]
That's kind of how it is.those two mods have dynamic assets as well unfortunately which means that even rho their blocks are always the same they don't have json models and EC jsut guesses where the texture could be. Works with most blocks but not all of them

**Comment by SettingDust** [comment]
Can't we try catch and set it to false automatically?

And is it possible to get the texture from "baked" like what Minecraft did?

**Comment by SettingDust** [comment]
I'm not quite sure what's the dynamic generating means. It's seems there is model for the block.
`[08:26:22] [Render thread/WARN] (Minecraft) Exception loading blockstate definition: 'everycomp:blockstates/mcf/betternether/anchor_tree_picket_fence.json' missing model for variant: 'everycomp:mcf/betternether/anchor_tree_picket_fence#east=true,fluidlogged=0,north=false,north_east=false,north_west=true,south=false,south_east=false,south_west=true,waterlogged=false,west=false'`
https://github.com/quiqueck/BetterNether/blob/1.19/src/main/resources/assets/betternether/models/block/anchor_tree_log.json
https://github.com/quiqueck/BetterNether/blob/1.19/src/main/resources/assets/betternether/blockstates/anchor_tree_log.json

**Comment by SettingDust** [comment]
The warns is gone with `mixin.perf.dynamic_resources=false` in moderfix

**Comment by MehVahdJukaar** [comment]
I'm working on that. Actually I thought I solved modern fix issue with latest moonlgiht patch as I added direct integration

**Comment by SettingDust** [comment]
I'm using `moonlight-1.19.2-2.2.39-fabric` with that fix

**Comment by Xelbayria** [comment]
if this problem is resolved, then please close this issue, thanks!
