### ISSUE TITLE
[Question] How to configure in local

### ISSUE THREAD

**Issue by SettingDust** [MehVahdJukaar/WoodGood#198]
I'm trying to import Gradle project by IDEA. But facing error. Tried update architectury loom to 1.2
```
Caused by: java.lang.RuntimeException: Failed to provide de.oceanlabs.mcp:mcp_config:1.19.2 : java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at net.fabricmc.loom.configuration.providers.forge.DependencyProviders.handleDependencies(DependencyProviders.java:111)
	at net.fabricmc.loom.configuration.CompileConfiguration.setupDependencyProviders(CompileConfiguration.java:371)
	at net.fabricmc.loom.configuration.CompileConfiguration.setupMinecraft(CompileConfiguration.java:199)
	at net.fabricmc.loom.configuration.CompileConfiguration.lambda$run$2(CompileConfiguration.java:114)
	... 195 more
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at net.minecraftforge.srgutils.InternalUtils.loadNamed(InternalUtils.java:53)
	at net.minecraftforge.srgutils.InternalUtils.load(InternalUtils.java:42)
	at net.minecraftforge.srgutils.IMappingFile.load(IMappingFile.java:41)
	at net.minecraftforge.srgutils.IMappingFile.load(IMappingFile.java:36)
	at net.minecraftforge.installertools.ChainMappings.process(ChainMappings.java:92)
	at net.minecraftforge.installertools.ConsoleTool.main(ConsoleTool.java:55)
	at net.fabricmc.loom.configuration.providers.forge.SrgProvider.provide(SrgProvider.java:103)
	at net.fabricmc.loom.configuration.providers.forge.DependencyProviders.handleDependencies(DependencyProviders.java:109)
	... 198 more
```

**Comment by SettingDust** [comment]
Should my own problem. Have no idea. But same result with another architechtury project

**Comment by MehVahdJukaar** [comment]
yeah idk what that is
