### ISSUE TITLE
[🐞]: Every Compat is incompatible with Architect's Palette

### ISSUE THREAD

**Issue by adozenlionsroaring** [MehVahdJukaar/WoodGood#398]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.23

### Moonlight Lib Version

moonlight-1.20-2.8.82

### Issue with mods

Architect's Palette (newly released for 1.20.1)

### Issue Detail

The just-released 1.20.1 version of Architect's Palette appears to have an incompatibility with Every Compat, as when the two are loaded together the game crashes. More specifically, the crash message names the "Board Block" from Architect's Palette as the origin of a "Class not found exception" that is causing Every Compat to fail (see log).

### OPTIONAL: Latest.log | Crash-report Attachment

	Failure message: Every Compat (everycomp) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.20-2.6.23
	Mod Issue URL: https://github.com/MehVahdJukaar/WoodGood/issues
	Exception message: java.lang.ClassNotFoundException: architectspalette.content.blocks.BoardBlock
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at net.mehvahdjukaar.every_compat.forge.EveryCompatForge.lambda$new$18(EveryCompatForge.java:82) ~[everycomp-1.20-2.6.23.jar%23160!/:?] {re:classloading}
	at net.mehvahdjukaar.every_compat.EveryCompat.addModule(EveryCompat.java:162) ~[everycomp-1.20-2.6.23.jar%23160!/:?] {re:classloading}
	at net.mehvahdjukaar.every_compat.forge.EveryCompatForge.<init>(EveryCompatForge.java:82) ~[everycomp-1.20-2.6.23.jar%23160!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23164!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23163!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by adozenlionsroaring** [comment]
I've just tried out the newest version of Every Compat and can confirm that it now works with Architect's Palette for 1.20.1. :) Yay, thank you so much! I'll close this issue now.
