### ISSUE TITLE
[🐞]: Mod fails to load with the latest version of "Macaw Paths"

### ISSUE THREAD

**Issue by bitmochibit** [MehVahdJukaar/WoodGood#410]
### Before Continuing:

- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] Always check you are using the latest version of the mods and its dependencies
- [ ] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

everycompat-1.19.2-2.5.16

### Moonlight Lib Version

moonlight-1.19.2-2.3.6

### Issue with mods

Macaw's Paths and Pavings v. 1.0.4

### Issue Detail

The mod doesn't load

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/14036787/latest.log)

### OPTIONAL: To Produce

Install the last version of Macaw's Paths and Pavings

**Comment by bitmochibit** [comment]
I accidentally uploaded the log with the previous version of EveryCompat, but the issue persists with the new version.


[23Jan2024 22:49:59.417] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: everycomp, class net.mehvahdjukaar.every_compat.forge.EveryCompatForge
java.lang.NoSuchFieldError: PathsItemGroup
	at net.mehvahdjukaar.every_compat.modules.forge.mcaw.MacawPathsModule.<init>(MacawPathsModule.java:24) ~[everycomp-1.19.2-2.5.16.jar%23476!/:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.addModule(EveryCompat.java:167) ~[everycomp-1.19.2-2.5.16.jar%23476!/:?]
	at net.mehvahdjukaar.every_compat.forge.EveryCompatForge.<init>(EveryCompatForge.java:98) ~[everycomp-1.19.2-2.5.16.jar%23476!/:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.7.jar%23621!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.3.7.jar%23620!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by MehVahdJukaar** [comment]
Downgrade or remove macaw paths
