### ISSUE TITLE
Fabric build crashes on launch as of 10/7/2022

### ISSUE THREAD

**Issue by dopadream** [MehVahdJukaar/WoodGood#60]
java.lang.AbstractMethodError: Receiver class net.mehvahdjukaar.moonlight.api.platform.fabric.ClientPlatformHelperImpl$3 does not define or inherit an implementation of the resolved method 'abstract java.util.concurrent.CompletableFuture reload(net.minecraft.server.packs.resources.PreparableReloadListener$PreparationBarrier, net.minecraft.server.packs.resources.ResourceManager, net.minecraft.util.profiling.ProfilerFiller, net.minecraft.util.profiling.ProfilerFiller, java.util.concurrent.Executor, java.util.concurrent.Executor)' of interface net.minecraft.server.packs.resources.PreparableReloadListener.
	at net.minecraft.server.packs.resources.SimpleReloadInstance.method_18368(SimpleReloadInstance.java:32)
	at net.minecraft.server.packs.resources.SimpleReloadInstance.<init>(SimpleReloadInstance.java:44)
	at net.minecraft.server.packs.resources.SimpleReloadInstance.of(SimpleReloadInstance.java:32)
	at net.minecraft.server.packs.resources.SimpleReloadInstance.create(SimpleReloadInstance.java:101)
	at net.minecraft.server.packs.resources.ReloadableResourceManager.createReload(ReloadableResourceManager.java:47)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:648)
	at net.minecraft.client.main.Main.run(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)

**Comment by Xelbayria** [comment]
is this issue solved? If yes, then please close this. 

if not, then please fill out:
- Minecraft version:
- loader: (Fabric or Forge): **Fabric**
- Which mods have an issue with EveryCompat:

**Comment by Xelbayria** [comment]
Please attach a full log file here. Haven't heard from you yet. If I don't hear from you for a while, I'll close this due to no replying. You can re-open this if you have the same issue as before.
