### ISSUE TITLE
[IDE - IntelliJ] Errors when starting Forge client

### ISSUE THREAD

**Issue by cech12** [MehVahdJukaar/WoodGood#87]
Hey,

I get the following error when I want to start the client:

```
[Architectury Transformer] Architectury Runtime 5.2.72
[Architectury Transformer] Read classpath in 3.863 s
[Architectury Transformer] Listening at D:\Projekte\Minecraft\WoodGood\common\build\devlibs\everycomp-1.19.2-2.1.1-dev.jar
[15:31:07] [main/INFO] (Launcher) ModLauncher running: args [--launchTarget, forgeclientuserdev, --version, MOD_DEV, --assetIndex, 1.19.2-1.19, --assetsDir, C:\Users\Chris\.gradle\caches\fabric-loom\assets, --gameDir, ., --fml.forgeVersion, 43.1.47, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, -mixin.config, everycomp-common.mixins.json, -mixin.config, everycomp.mixins.json, --mixin.config, everycomp-common.mixins.json]
[15:31:07] [main/INFO] (Launcher) ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Eclipse Adoptium; OS Windows 10 arch amd64 version 10.0
Exception in thread "main" java.lang.module.ResolutionException: Module fmlloader reads more than one module named org.spongepowered.mixin
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:722)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:130)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)
```

Steps:

1.  Clone projekt and load it in IntelliJ
2. sync/refresh Gradle
3. run "genEclipseRuns" task (there is no task for IntelliJ)
4. run "Minecraft Client (:forge)"

**Comment by MehVahdJukaar** [comment]
You should not run gen eclipse runs. Architectury already generates runs for you

**Comment by MehVahdJukaar** [comment]
For more you could ask on architectury discord because I don't use eclipse myself

**Comment by cech12** [comment]
I dont use eclipse xD Which tasks should I use to let Architecury generate these runs?

**Comment by MehVahdJukaar** [comment]
None, you should already have them. If you don't delete the (broken)ones you have, refresh gradle and reboot intellij and they will be there

**Comment by cech12** [comment]
Ahh! That did the trick! :)
